"""Add rating column

Revision ID: 347bf18859fe
Revises: 
Create Date: 2025-10-19 20:00:32.901611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347bf18859fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_review', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
