"""Added a created_date column

Revision ID: e75c277a6804
Revises: 347bf18859fe
Create Date: 2025-10-19 20:02:14.341507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75c277a6804'
down_revision = '347bf18859fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_review', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
