services:
  backend:
    build: ./backend
    ports:
      - "5860:5860"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
